name: "♻️ Update GitHub Profile Activity / Metrics"

on:
  schedule:
    - cron: "0 3 * * *" # daily at 03:00 UTC
  workflow_dispatch:

jobs:
  update-profile-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update profile README metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: elvisowusu
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Accra
          plugin_activity: yes
          plugin_activity_limit: 6
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: public
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_followup: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          output_action: commit

      - name: Push metrics to repository
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "♻️ Update GitHub profile metrics"
          file_pattern: "metrics.svg"
          skip_fetch: false
          skip_checkout: false
